origens:
  urls: "*"

custom:
  db:
    host: cluster0.xn0yn5w.mongodb.net
    port: 27017           # Se ignora si usas SRV
    name: fondopension
    username: lukhack
    password: nUhlYBl4jXoYbqxu    # Puedes URL-encodearla si trae caracteres especiales
    auth-db: admin
    auto-index-creation: true